services:
  db:
    image: mysql:8.0
    container_name: ${DB_HOST}
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./bdd/csb_full_dump_20260103_121355.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - csb-network

  backend:
    build: ./backend
    container_name: vaccins-backend
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=*
    depends_on:
      - db
    networks:
      - csb-network
      - dokploy-network
    labels:
      - "traefik.enable=true"
      # Router HTTPS (sécurisé)
      - "traefik.http.routers.csb-api-secure.rule=Host(`api.csb.madahoff.com`)"
      - "traefik.http.routers.csb-api-secure.entrypoints=websecure"
      - "traefik.http.routers.csb-api-secure.tls=true"
      - "traefik.http.routers.csb-api-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.csb-api-secure.service=csb-api-service"
      # Router HTTP (redirection vers HTTPS)
      - "traefik.http.routers.csb-api.rule=Host(`api.csb.madahoff.com`)"
      - "traefik.http.routers.csb-api.entrypoints=web"
      - "traefik.http.routers.csb-api.middlewares=redirect-to-https"
      # Service (port interne du container)
      - "traefik.http.services.csb-api-service.loadbalancer.server.port=3000"

  frontend:
    build: ./frontend
    container_name: vaccins-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - PROD=${PROD}
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      # Router HTTPS (sécurisé)
      - "traefik.http.routers.csb-web-secure.rule=Host(`csb.madahoff.com`)"
      - "traefik.http.routers.csb-web-secure.entrypoints=websecure"
      - "traefik.http.routers.csb-web-secure.tls=true"
      - "traefik.http.routers.csb-web-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.csb-web-secure.service=csb-web-service"
      # Router HTTP (redirection vers HTTPS)
      - "traefik.http.routers.csb-web.rule=Host(`csb.madahoff.com`)"
      - "traefik.http.routers.csb-web.entrypoints=web"
      - "traefik.http.routers.csb-web.middlewares=redirect-to-https"
      # Service (port interne du container)
      - "traefik.http.services.csb-web-service.loadbalancer.server.port=80"

volumes:
  mysql_data:
    driver: local

networks:
  csb-network:
    driver: bridge
  dokploy-network:
    external: true
